//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDeliveryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID { get; set; }
        public int IDComputerDetails { get; set; }
        public int IDOrder { get; set; }
    
        public virtual ComputerDetails ComputerDetails { get; set; }
        public virtual Order Order { get; set; }
    }
}
