//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDeliveryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Basket = new HashSet<Basket>();
        }
    
        public int ID { get; set; }
        public int IDExecuter { get; set; }
        public int IDComputerDetails { get; set; }
        public int IDClient { get; set; }
        public int IDStatus { get; set; }
        public System.DateTime DateOrder { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual Client Client { get; set; }
        public virtual ComputerDetails ComputerDetails { get; set; }
        public virtual Executer Executer { get; set; }
        public virtual Status Status { get; set; }
    }
}
